"""Convert a netlist, symbol-pose JSON, and wire JSON back into an LTspice ASC file."""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
from typing import Dict
from typing import Iterable
from typing import List
from typing import Mapping
from typing import Optional
from typing import Sequence
from typing import Tuple

import numpy as np

from . import ltspice_asc as _asc
from . import ltspice_asc_to_netlist as _asc_to_netlist
from . import ltspice_net as _net
from .pathtracing import place_wires_into_groups

ConversionResult = Tuple[bool, str, int]
Point = Tuple[int, int]
WireRow = Tuple[int, int, int, int]

_OK_RESULT: ConversionResult = (True, "OK", 0)
_LINE_NUMBER_PATTERN = re.compile(r"Line (?P<line>\d+)")
_AUTO_NET_PATTERN = re.compile(r"^N\d{3}$", re.IGNORECASE)
_CORE_SYMBOL_KEYS = {"SYMBOL", "X", "Y", "ORIENTATION", "RECTANGLE", "PINS"}
_ASC_ATTRIBUTE_ORDER = (
    "Value",
    "Value2",
    "SpiceLine",
    "SpiceLine2",
    "SpiceModel",
    "Type",
    "ModelFile",
)
_ATTRIBUTE_KEY_ALIASES = {
    "VALUE": "Value",
    "VALUE2": "Value2",
    "SPICELINE": "SpiceLine",
    "SPICELINE2": "SpiceLine2",
    "SPICEMODEL": "SpiceModel",
    "TYPE": "Type",
    "MODELFILE": "ModelFile",
}
_IGNORED_LEADING_COMMENT_PATTERNS = (
    re.compile(r"^[A-Za-z]:\\.*\.asc$", re.IGNORECASE),
    re.compile(r"^Generated by LTspice\b", re.IGNORECASE),
)


@dataclass(frozen=True)
class LogicalLine:
    line_number: int
    kind: str
    text: str


@dataclass(frozen=True)
class TextRecord:
    payload: str
    font_size: int
    estimated_height: int


def ltspice_netlist_symbol_wire_to_asc(
    netlist_filepath: str,
    symbol_pose_filepath: str,
    wire_filepath: str,
    asc_filepath_out: str,
    convert_settings: Mapping[str, object],
) -> ConversionResult:
    if not isinstance(convert_settings, Mapping):
        return False, "INVALID_CONVERT_SETTINGS", 0
    voltage_must_have_dc = _net._resolve_voltage_must_have_dc(convert_settings)
    if voltage_must_have_dc is None:
        return False, "INVALID_CONVERT_SETTINGS", 0
    if not _coerce_path_success(asc_filepath_out):
        return False, "INVALID_OUTPUT_PATH", 0
    version_text = _resolve_ltspice_version(convert_settings)
    if version_text is None:
        return False, "INVALID_CONVERT_SETTINGS", 0
    format_validation_result = _net.is_valid_ltspice_netlist_format(netlist_filepath)
    if not format_validation_result[0]:
        return False, "INVALID_NETLIST_FILE", _line_number_from_message(format_validation_result[1], 0)
    read_result = _net._read_text_file_lines(netlist_filepath)
    if not read_result[0]:
        return False, "NETLIST_READ_ERROR", 0
    logical_lines = _collect_logical_lines(read_result[1])
    wire_map_result = _read_wire_map(wire_filepath)
    if not wire_map_result[0]:
        return wire_map_result[1]
    symbol_pose_result = _read_symbol_pose_mapping(symbol_pose_filepath)
    if not symbol_pose_result[0]:
        return symbol_pose_result[1]
    symbol_pose = symbol_pose_result[2]
    search_roots = _asc_to_netlist._resolve_search_roots_for_asc(netlist_filepath, convert_settings)
    symbol_paths = _asc_to_netlist._build_symbol_filepath_lookup(search_roots)
    instance_payload_attributes = _build_instance_payload_attributes(
        logical_lines,
        voltage_must_have_dc,
    )
    try:
        asc_lines = _build_asc_lines(
            version_text,
            wire_map_result[2],
            symbol_pose,
            logical_lines,
            instance_payload_attributes,
            symbol_paths,
        )
    except ValueError as error:
        return False, str(error), 0
    write_result = _write_latin1_asc_file(asc_filepath_out, asc_lines)
    if not write_result[0]:
        return False, write_result[1], 0
    validation_result = _asc.is_valid_ltspice_asc_file(asc_filepath_out)
    if not validation_result[0]:
        return False, "INVALID_GENERATED_ASC", _line_number_from_message(validation_result[1], 0)
    return _OK_RESULT


def _build_asc_lines(
    version_text: str,
    wire_map: Mapping[str, Sequence[Sequence[int]]],
    symbol_pose: Mapping[str, Mapping[str, object]],
    logical_lines: Sequence[LogicalLine],
    instance_payload_attributes: Mapping[str, Mapping[str, str]],
    symbol_paths: Mapping[str, str],
) -> Tuple[str, ...]:
    wire_lines: List[str] = []
    flag_lines: List[str] = []
    all_points: List[Point] = []
    for net_name, raw_wire_rows in wire_map.items():
        normalized_wire_rows = _normalize_wire_rows(raw_wire_rows)
        for wire_row in normalized_wire_rows:
            wire_lines.append(f"WIRE {wire_row[0]} {wire_row[1]} {wire_row[2]} {wire_row[3]}")
            all_points.extend(((wire_row[0], wire_row[1]), (wire_row[2], wire_row[3])))
        flag_lines.extend(_flag_lines_for_net(net_name, normalized_wire_rows))
    symbol_lines: List[str] = []
    symbol_bounds = _collect_symbol_bounds(symbol_pose)
    all_points.extend(symbol_bounds)
    for instance_name, raw_symbol_entry in symbol_pose.items():
        symbol_entry = dict(raw_symbol_entry)
        symbol_name = str(symbol_entry.get("SYMBOL", "")).strip()
        if symbol_name == "":
            raise ValueError("SYMBOL_POSE_PARSE_ERROR")
        symbol_x = int(symbol_entry.get("X", 0))
        symbol_y = int(symbol_entry.get("Y", 0))
        orientation = str(symbol_entry.get("ORIENTATION", "R0")).strip().upper() or "R0"
        symbol_lines.append(f"SYMBOL {symbol_name} {symbol_x} {symbol_y} {orientation}")
        for window_line in _load_symbol_window_lines(symbol_name, symbol_paths):
            symbol_lines.append(window_line)
        symbol_lines.append(f"SYMATTR InstName {instance_name}")
        merged_attributes = _merge_symbol_attributes(
            symbol_entry,
            instance_payload_attributes.get(instance_name, {}),
            _load_symbol_default_attributes(symbol_name, symbol_paths),
        )
        for attribute_key in _ordered_attribute_keys(merged_attributes):
            symbol_lines.append(f"SYMATTR {attribute_key} {merged_attributes[attribute_key]}")
    text_records = _collect_text_records(logical_lines, symbol_pose)
    if not _has_active_analysis_text_record(text_records):
        text_records = (*text_records, TextRecord(payload="!.op", font_size=2, estimated_height=_estimate_text_height("!.op", 2)))
    sheet_width, sheet_height = _compute_sheet_size(all_points, text_records)
    text_lines = _layout_text_records(text_records, all_points)
    return (
        f"Version {version_text}",
        f"SHEET 1 {sheet_width} {sheet_height}",
        *wire_lines,
        *flag_lines,
        *symbol_lines,
        *text_lines,
    )


def _read_wire_map(wire_filepath: str) -> Tuple[bool, ConversionResult, Dict[str, List[List[int]]]]:
    try:
        wire_path = Path(os.fspath(wire_filepath))
    except TypeError:
        return False, (False, "INVALID_WIRE_PATH", 0), {}
    try:
        wire_json = json.loads(wire_path.read_text(encoding="utf-8"))
    except OSError:
        return False, (False, "WIRE_READ_ERROR", 0), {}
    except json.JSONDecodeError as error:
        return False, (False, "WIRE_PARSE_ERROR", error.lineno), {}
    if not isinstance(wire_json, dict):
        return False, (False, "WIRE_PARSE_ERROR", 0), {}
    normalized_wire_map: Dict[str, List[List[int]]] = {}
    for net_name, raw_rows in wire_json.items():
        try:
            row_list = [[int(value) for value in row] for row in raw_rows]
        except (TypeError, ValueError):
            return False, (False, "WIRE_PARSE_ERROR", 0), {}
        normalized_wire_map[str(net_name)] = row_list
    return True, _OK_RESULT, normalized_wire_map


def _read_symbol_pose_mapping(symbol_pose_filepath: str) -> Tuple[bool, ConversionResult, Dict[str, Dict[str, object]]]:
    try:
        symbol_path = Path(os.fspath(symbol_pose_filepath))
    except TypeError:
        return False, (False, "INVALID_SYMBOL_POSE_PATH", 0), {}
    try:
        symbol_json = json.loads(symbol_path.read_text(encoding="utf-8"))
    except OSError:
        return False, (False, "SYMBOL_POSE_READ_ERROR", 0), {}
    except json.JSONDecodeError as error:
        return False, (False, "SYMBOL_POSE_PARSE_ERROR", error.lineno), {}
    if not isinstance(symbol_json, dict):
        return False, (False, "SYMBOL_POSE_PARSE_ERROR", 0), {}
    normalized_mapping: Dict[str, Dict[str, object]] = {}
    for instance_name, raw_entry in symbol_json.items():
        if not isinstance(raw_entry, dict):
            return False, (False, "SYMBOL_POSE_PARSE_ERROR", 0), {}
        normalized_mapping[str(instance_name)] = dict(raw_entry)
    return True, _OK_RESULT, normalized_mapping


def _collect_logical_lines(lines: Sequence[str]) -> Tuple[LogicalLine, ...]:
    logical_lines: List[LogicalLine] = []
    current_line_number = 0
    current_kind = ""
    current_parts: List[str] = []
    seen_code_line = False
    for line_number, raw_line in enumerate(lines, start=1):
        classification_result = _net._classify_line(raw_line)
        if not classification_result[0]:
            continue
        kind = classification_result[1]
        if kind == "blank":
            if current_parts:
                logical_lines.append(LogicalLine(current_line_number, current_kind, " ".join(current_parts).strip()))
                current_line_number = 0
                current_kind = ""
                current_parts = []
            continue
        if kind == "comment":
            if current_parts:
                logical_lines.append(LogicalLine(current_line_number, current_kind, " ".join(current_parts).strip()))
                current_line_number = 0
                current_kind = ""
                current_parts = []
            stripped_line = raw_line.lstrip()
            comment_kind = "disabled_directive" if stripped_line.startswith(";") else "comment"
            comment_text = stripped_line[1:].strip()
            if not seen_code_line and _should_ignore_leading_comment(comment_text):
                continue
            logical_lines.append(LogicalLine(line_number, comment_kind, comment_text))
            continue
        if kind == "continuation":
            continuation_text = _net._strip_semicolon_comment(raw_line).lstrip()[1:].strip()
            if current_parts and continuation_text != "":
                current_parts.append(continuation_text)
            continue
        code_text = _net._strip_semicolon_comment(raw_line).strip()
        if code_text == "":
            continue
        if current_parts:
            logical_lines.append(LogicalLine(current_line_number, current_kind, " ".join(current_parts).strip()))
        current_line_number = line_number
        current_kind = kind
        current_parts = [code_text]
        seen_code_line = True
    if current_parts:
        logical_lines.append(LogicalLine(current_line_number, current_kind, " ".join(current_parts).strip()))
    return tuple(logical_lines)


def _should_ignore_leading_comment(comment_text: str) -> bool:
    stripped_comment = comment_text.strip()
    if stripped_comment == "":
        return True
    return any(pattern.match(stripped_comment) is not None for pattern in _IGNORED_LEADING_COMMENT_PATTERNS)


def _normalize_wire_rows(raw_wire_rows: Sequence[Sequence[int]]) -> Tuple[WireRow, ...]:
    normalized_rows: List[WireRow] = []
    for raw_row in raw_wire_rows:
        if len(raw_row) != 4:
            raise ValueError("WIRE_PARSE_ERROR")
        normalized_rows.append((int(raw_row[0]), int(raw_row[1]), int(raw_row[2]), int(raw_row[3])))
    return tuple(normalized_rows)


def _flag_line_for_net(net_name: str, wire_rows: Sequence[WireRow]) -> Optional[str]:
    if not wire_rows:
        return None
    normalized_net_name = net_name.strip()
    if normalized_net_name == "":
        return None
    upper_net_name = normalized_net_name.upper()
    points = [point for wire_row in wire_rows for point in ((wire_row[0], wire_row[1]), (wire_row[2], wire_row[3]))]
    if upper_net_name in {"0", "GND"}:
        flag_point = max(points, key=lambda point: (point[1], point[0]))
        flag_name = "0" if upper_net_name == "0" else "GND"
        return f"FLAG {flag_point[0]} {flag_point[1]} {flag_name}"
    if _AUTO_NET_PATTERN.match(normalized_net_name) is not None:
        return None
    flag_point = min(points, key=lambda point: (point[1], point[0]))
    return f"FLAG {flag_point[0]} {flag_point[1]} {normalized_net_name}"


def _flag_lines_for_net(net_name: str, wire_rows: Sequence[WireRow]) -> Tuple[str, ...]:
    """Return labels needed to make every disconnected wire group one net."""

    if not wire_rows:
        return ()
    wire_groups = place_wires_into_groups(np.asarray(wire_rows, dtype=int))
    if len(wire_groups) <= 1:
        flag_line = _flag_line_for_net(net_name, wire_rows)
        return (flag_line,) if flag_line is not None else ()
    normalized_net_name = net_name.strip()
    if normalized_net_name == "":
        return ()
    flag_name = "0" if normalized_net_name.upper() == "0" else normalized_net_name
    flag_lines: List[str] = []
    for wire_group in wire_groups:
        group_rows = tuple(tuple(int(value) for value in row) for row in wire_group.tolist())
        points = [
            point
            for wire_row in group_rows
            for point in ((wire_row[0], wire_row[1]), (wire_row[2], wire_row[3]))
        ]
        if flag_name.upper() in {"0", "GND"}:
            flag_point = max(points, key=lambda point: (point[1], point[0]))
        else:
            flag_point = min(points, key=lambda point: (point[1], point[0]))
        flag_lines.append(f"FLAG {flag_point[0]} {flag_point[1]} {flag_name}")
    return tuple(flag_lines)


def _collect_symbol_bounds(symbol_pose: Mapping[str, Mapping[str, object]]) -> List[Point]:
    bounds: List[Point] = []
    for symbol_entry in symbol_pose.values():
        raw_rectangle = symbol_entry.get("RECTANGLE")
        if not isinstance(raw_rectangle, list) or len(raw_rectangle) != 2:
            symbol_x = int(symbol_entry.get("X", 0))
            symbol_y = int(symbol_entry.get("Y", 0))
            bounds.append((symbol_x, symbol_y))
            continue
        try:
            first_point = raw_rectangle[0]
            second_point = raw_rectangle[1]
            bounds.append((int(first_point[0]), int(first_point[1])))
            bounds.append((int(second_point[0]), int(second_point[1])))
        except (TypeError, ValueError, IndexError):
            symbol_x = int(symbol_entry.get("X", 0))
            symbol_y = int(symbol_entry.get("Y", 0))
            bounds.append((symbol_x, symbol_y))
    return bounds


def _load_symbol_window_lines(symbol_name: str, symbol_paths: Mapping[str, str]) -> Tuple[str, ...]:
    symbol_filepath = _asc_to_netlist._resolve_symbol_filepath(symbol_name, symbol_paths)
    if symbol_filepath is None:
        return ()
    read_result = _asc._read_text_file_lines(symbol_filepath)
    if not read_result[0]:
        return ()
    return tuple(
        raw_line.strip()
        for raw_line in read_result[1]
        if raw_line.strip().upper().startswith("WINDOW ")
    )


def _load_symbol_default_attributes(
    symbol_name: str,
    symbol_paths: Mapping[str, str],
) -> Dict[str, str]:
    """Read defaults from the selected ASY instead of duplicating them."""

    symbol_filepath = _asc_to_netlist._resolve_symbol_filepath(symbol_name, symbol_paths)
    if symbol_filepath is None:
        return {}
    read_result = _asc._read_text_file_lines(symbol_filepath)
    if not read_result[0]:
        return {}
    defaults: Dict[str, str] = {}
    for raw_line in read_result[1]:
        stripped_line = raw_line.strip()
        if not stripped_line.upper().startswith("SYMATTR "):
            continue
        tokens = stripped_line.split(maxsplit=2)
        if len(tokens) < 3:
            continue
        normalized_key = _ATTRIBUTE_KEY_ALIASES.get(tokens[1].upper())
        if normalized_key is not None:
            defaults[normalized_key] = tokens[2].strip()
    return defaults


def _merge_symbol_attributes(
    symbol_entry: Mapping[str, object],
    payload_attributes: Mapping[str, str],
    symbol_defaults: Optional[Mapping[str, str]] = None,
) -> Dict[str, str]:
    defaults = symbol_defaults or {}
    merged_attributes: Dict[str, str] = {}
    for raw_key, raw_value in symbol_entry.items():
        normalized_key = _ATTRIBUTE_KEY_ALIASES.get(str(raw_key).upper())
        if normalized_key is None or str(raw_key).upper() in _CORE_SYMBOL_KEYS:
            continue
        clean_value = _clean_optional_text(raw_value)
        if clean_value != "":
            merged_attributes[normalized_key] = clean_value
    for attribute_key, attribute_value in payload_attributes.items():
        if attribute_key in merged_attributes or attribute_value.strip() == "":
            continue
        payload_value = attribute_value.strip()
        if attribute_key == "Value" and "SpiceLine" in merged_attributes:
            payload_tokens = payload_value.split()
            explicit_spice_tokens = merged_attributes["SpiceLine"].split()
            if (
                explicit_spice_tokens
                and payload_tokens[-len(explicit_spice_tokens) :] == explicit_spice_tokens
            ):
                payload_value = " ".join(payload_tokens[: -len(explicit_spice_tokens)])
        if attribute_key == "SpiceLine":
            combined_payload_value = " ".join(
                value
                for value in (
                    payload_attributes.get("Value", "").strip(),
                    payload_value,
                )
                if value != ""
            )
            if combined_payload_value == merged_attributes.get("Value", "").strip():
                continue
            default_spice_tokens = " ".join(
                value
                for value in (
                    defaults.get("Value2", "").strip(),
                    defaults.get("SpiceLine", "").strip(),
                    defaults.get("SpiceLine2", "").strip(),
                )
                if value != ""
            ).split()
            payload_tokens = payload_value.split()
            if default_spice_tokens and payload_tokens[: len(default_spice_tokens)] == default_spice_tokens:
                payload_value = " ".join(payload_tokens[len(default_spice_tokens) :])
        elif payload_value == defaults.get(attribute_key, "").strip():
            payload_value = ""
        if payload_value != "":
            merged_attributes[attribute_key] = payload_value
    return merged_attributes


def _ordered_attribute_keys(attributes: Mapping[str, str]) -> Tuple[str, ...]:
    preferred_keys = [attribute_key for attribute_key in _ASC_ATTRIBUTE_ORDER if attribute_key in attributes]
    remaining_keys = sorted(attribute_key for attribute_key in attributes if attribute_key not in _ASC_ATTRIBUTE_ORDER)
    return tuple(preferred_keys + remaining_keys)


def _build_instance_payload_attributes(
    logical_lines: Sequence[LogicalLine],
    voltage_must_have_dc: bool,
) -> Dict[str, Dict[str, str]]:
    attributes_by_instance: Dict[str, Dict[str, str]] = {}
    for logical_line in logical_lines:
        if logical_line.kind != "device":
            continue
        tokens = _net._normalize_voltage_source_tokens(
            logical_line.text.split(),
            voltage_must_have_dc,
        )
        if not tokens or tokens[0][0].upper() == "K":
            continue
        instance_name = _normalize_instance_name(tokens[0])
        if instance_name == "":
            continue
        attributes_by_instance[instance_name] = _payload_attributes_from_tokens(tokens)
    return attributes_by_instance


def _payload_attributes_from_tokens(tokens: Sequence[str]) -> Dict[str, str]:
    node_result = _net._extract_nodes(tokens)
    if not node_result[0]:
        return {}
    payload_tokens = list(tokens[1 + len(node_result[1]) :])
    if not payload_tokens:
        return {}
    prefix = tokens[0][0].upper()
    attributes: Dict[str, str] = {}
    if prefix in {"V", "I"}:
        if "AC" in (token.upper() for token in payload_tokens):
            ac_index = next(index for index, token in enumerate(payload_tokens) if token.upper() == "AC")
            value_text = " ".join(payload_tokens[:ac_index]).strip()
            value2_text = " ".join(payload_tokens[ac_index:]).strip()
            if value_text != "":
                attributes["Value"] = value_text
            if value2_text != "":
                attributes["Value2"] = value2_text
            return attributes
        attributes["Value"] = " ".join(payload_tokens).strip()
        return attributes
    if prefix in {"R", "C", "L"}:
        attributes["Value"] = payload_tokens[0].strip()
        if len(payload_tokens) > 1:
            attributes["SpiceLine"] = " ".join(payload_tokens[1:]).strip()
        return attributes
    if prefix in {"D", "J", "M", "Q", "S", "W", "Z"}:
        model_token = payload_tokens[0].strip()
        if model_token != "":
            attributes["Value"] = model_token
        if len(payload_tokens) > 1:
            attributes["SpiceLine"] = " ".join(payload_tokens[1:]).strip()
        return attributes
    if prefix == "X":
        attributes["Value"] = payload_tokens[0].strip()
        if len(payload_tokens) > 1:
            attributes["SpiceLine"] = " ".join(payload_tokens[1:]).strip()
        return attributes
    if prefix in {"B", "E", "F", "G", "H"}:
        attributes["Value"] = " ".join(payload_tokens).strip()
        return attributes
    return attributes


def _collect_text_records(
    logical_lines: Sequence[LogicalLine],
    symbol_pose: Mapping[str, Mapping[str, object]],
) -> Tuple[TextRecord, ...]:
    text_records: List[TextRecord] = []
    for logical_line in logical_lines:
        if logical_line.kind == "device":
            tokens = logical_line.text.split()
            if not tokens:
                continue
            instance_name = _normalize_instance_name(tokens[0])
            if tokens[0][0].upper() == "K" or instance_name not in symbol_pose:
                payload = f"!{logical_line.text}"
                text_records.append(
                    TextRecord(
                        payload=payload,
                        font_size=2,
                        estimated_height=_estimate_text_height(payload, 2),
                    )
                )
            continue
        if logical_line.kind == "directive":
            if logical_line.text.lower() in {".backanno", ".end"}:
                continue
            payload = f"!{_normalize_directive_text(logical_line.text)}"
            text_records.append(
                TextRecord(
                    payload=payload,
                    font_size=2,
                    estimated_height=_estimate_text_height(payload, 2),
                )
            )
            continue
        if logical_line.kind == "comment":
            if logical_line.text.strip() == "":
                continue
            font_size = 4 if _looks_like_title_comment(logical_line.text) else 2
            payload = f";{logical_line.text}"
            text_records.append(
                TextRecord(
                    payload=payload,
                    font_size=font_size,
                    estimated_height=_estimate_text_height(payload, font_size),
                )
            )
            continue
        if logical_line.kind == "disabled_directive":
            if logical_line.text.strip() == "":
                continue
            payload = f"!;{logical_line.text}"
            text_records.append(
                TextRecord(
                    payload=payload,
                    font_size=2,
                    estimated_height=_estimate_text_height(payload, 2),
                )
            )
    return tuple(text_records)


def _has_active_analysis_text_record(text_records: Sequence[TextRecord]) -> bool:
    for text_record in text_records:
        if not text_record.payload.startswith("!.") or text_record.payload.startswith("!;"):
            continue
        directive_result = _asc._parse_directive_name(text_record.payload[1:])
        if directive_result[0] and directive_result[1] in _asc._ANALYSIS_DIRECTIVES:
            return True
    return False


def _normalize_directive_text(directive_text: str) -> str:
    stripped_text = directive_text.strip()
    if stripped_text.lower().startswith(".function "):
        return f".func {stripped_text[10:].lstrip()}"
    return stripped_text


def _looks_like_title_comment(comment_text: str) -> bool:
    stripped_comment = comment_text.strip()
    return "\\n" not in stripped_comment and len(stripped_comment) <= 64


def _estimate_text_height(payload: str, font_size: int) -> int:
    logical_line_count = max(payload.count("\\n") + 1, 1)
    line_height = 24 if font_size <= 2 else 40
    return logical_line_count * line_height


def _compute_sheet_size(all_points: Sequence[Point], text_records: Sequence[TextRecord]) -> Tuple[int, int]:
    if all_points:
        min_x = min(point[0] for point in all_points)
        max_x = max(point[0] for point in all_points)
        min_y = min(point[1] for point in all_points)
        max_y = max(point[1] for point in all_points)
    else:
        min_x = max_x = min_y = max_y = 0
    content_width = max_x - min_x
    content_height = max_y - min_y
    text_height = sum(record.estimated_height + 16 for record in text_records)
    sheet_width = max(content_width + 256, 880)
    sheet_height = max(content_height + text_height + 256, 680)
    return sheet_width, sheet_height


def _layout_text_records(text_records: Sequence[TextRecord], all_points: Sequence[Point]) -> Tuple[str, ...]:
    if not text_records:
        return ()
    if all_points:
        max_x = max(point[0] for point in all_points)
        max_y = max(point[1] for point in all_points)
        min_y = min(point[1] for point in all_points)
    else:
        max_x = 0
        max_y = 0
        min_y = 0
    text_x = max_x + 48
    current_y = max_y + 48
    text_lines: List[str] = []
    for text_record in text_records:
        text_lines.append(f"TEXT {text_x} {current_y} Left {text_record.font_size} {text_record.payload}")
        current_y += text_record.estimated_height + 16
    return tuple(text_lines)


def _resolve_ltspice_version(convert_settings: Mapping[str, object]) -> Optional[str]:
    raw_version = convert_settings.get("ltspice_version", "4.1")
    if isinstance(raw_version, bool):
        return None
    if isinstance(raw_version, int):
        return str(raw_version)
    if isinstance(raw_version, float):
        return f"{raw_version:g}"
    version_text = str(raw_version).strip()
    return version_text if version_text != "" else None


def _write_latin1_asc_file(filepath: str, lines: Iterable[str]) -> Tuple[bool, str]:
    output_path_result = _asc._coerce_path(filepath)
    if not output_path_result[0]:
        return False, "INVALID_OUTPUT_PATH"
    output_path = Path(output_path_result[1])
    normalized_lines = [_normalize_latin1_text(line) for line in lines]
    file_text = "\n".join(normalized_lines) + "\n"
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(file_text.encode("latin-1"))
    except (OSError, UnicodeEncodeError):
        return False, "WRITE_ERROR"
    return True, "OK"


def _normalize_latin1_text(value: str) -> str:
    return value.replace("μ", "µ")


def _normalize_instance_name(instance_token: str) -> str:
    clean_token = instance_token.strip()
    if clean_token == "":
        return ""
    if "§" in clean_token:
        return clean_token.split("§", 1)[1].strip()
    return clean_token


def _clean_optional_text(value: object) -> str:
    cleaned_value = str(value).strip()
    if cleaned_value in {"", '""'}:
        return ""
    return cleaned_value


def _line_number_from_message(message: str, default_line: int) -> int:
    line_match = _LINE_NUMBER_PATTERN.search(message)
    if line_match is None:
        return default_line
    return int(line_match.group("line"))


def _coerce_path_success(filepath: str) -> bool:
    path_result = _asc._coerce_path(filepath)
    return bool(path_result[0])
